import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import yaml from 'js-yaml';
import { parseSections } from '../lib/job-profile-parser.mjs';
import { buildProfileObject, serializeProfileYml } from '../lib/emit-profile-yml.mjs';

const md = readFileSync(
  new URL('./fixtures/job-profile.fixture.md', import.meta.url),
  'utf-8',
);
const sectionsOf = (text) => parseSections(text);

test('candidate.full_name derives from ## Identity', () => {
  const obj = buildProfileObject(sectionsOf(md), { existingCvFormat: 'html' });
  assert.equal(obj.candidate.full_name, 'Jordan Rivera');
  assert.equal(obj.candidate.email, 'jordan.rivera@example.com');
});

test('candidate.location and location.city are distinct', () => {
  const obj = buildProfileObject(sectionsOf(md), {});
  assert.equal(obj.candidate.location, 'Greater Seattle Area, WA');
  assert.equal(obj.location.city, 'Bellevue');
});

test('target_roles.primary captures only the Primary block', () => {
  const obj = buildProfileObject(sectionsOf(md), {});
  assert.deepEqual(obj.target_roles.primary, [
    'Senior Software Engineer',
    'Developer Experience Engineer',
  ]);
});

test('archetypes parse name/level/fit from the GFM table', () => {
  const obj = buildProfileObject(sectionsOf(md), {});
  const dt = obj.target_roles.archetypes.find((a) => a.name === 'Developer Tools Engineer');
  assert.deepEqual(dt, { name: 'Developer Tools Engineer', level: 'Senior', fit: 'primary' });
});

test('narrative.headline pulls the Narrative > Headline line', () => {
  const obj = buildProfileObject(sectionsOf(md), {});
  assert.match(obj.narrative.headline, /^Globex SWE building developer-tools/);
  assert.ok(obj.narrative.superpowers.length >= 2);
});

test('compensation target_range strips wrapping quotes', () => {
  const obj = buildProfileObject(sectionsOf(md), {});
  assert.equal(obj.compensation.target_range, '$250K-350K base + equity + bonus');
  assert.equal(obj.compensation.currency, 'USD');
});

test('emitted YAML round-trips and preserves key order; cv.output_format carried forward', () => {
  const obj = buildProfileObject(sectionsOf(md), { existingCvFormat: 'latex' });
  const back = yaml.load(yaml.dump(obj));
  assert.deepEqual(Object.keys(back), [
    'candidate', 'target_roles', 'narrative', 'compensation', 'location', 'cv',
  ]);
  assert.equal(back.cv.output_format, 'latex');
});

test('serializeProfileYml prepends provenance header and stays loadable', () => {
  const obj = buildProfileObject(sectionsOf(md), { existingCvFormat: 'html' });
  const out = serializeProfileYml(obj, '2026-05-22');
  assert.match(out, /^# config\/profile\.yml/);
  assert.match(out, /Generated by scripts\/derive-from-job-profile\.mjs on 2026-05-22/);
  const body = out.slice(out.indexOf('\ncandidate:') + 1);
  assert.equal(yaml.load(body).candidate.full_name, 'Jordan Rivera');
});

test('missing ## Compensation throws (no silent empty emit)', () => {
  const s = sectionsOf(md);
  s.delete('Compensation');
  assert.throws(() => buildProfileObject(s, {}), /missing required "## Compensation"/);
});

test('required field still <FILL IN> throws instead of leaking placeholder', () => {
  const broken = md.replace('Jordan Rivera', '<FILL IN: name>');
  assert.throws(() => buildProfileObject(sectionsOf(broken), {}), /<FILL IN>/);
});
